export const UPDATE_IMAGE_PATH = 'UPDATE_IMAGE_PATH';
export const READ_FILE_SUCCESS = 'READ_FILE_SUCCESS';
export const READ_FILE_FAIL = 'READ_FILE_FAIL';

export const IMAGE_LOAD_SUCCESS = 'IMAGE_LOAD_SUCCESS';
export const IMAGE_LOAD_FAIL = 'IMAGE_LOAD_FAIL';


export const ROTATE_IMAGE = 'ROTATE_IMAGE'; 
export const ZOOM_IN_IMAGE = 'ZOOM_IN_IMAGE';
export const ZOOM_OUT_IMAGE = 'ZOOM_OUT_IMAGE';
export const PAN_IMAGE = 'PAN_IMAGE';
export const UPDATE_CAPTION = 'UPDATE_CAPTION';
export const UPDATE_DATE = 'UPDATE_DATE';
export const UPDATE_ASSHOLE_NAME = 'UPDATE_ASSHOLE_NAME';
export const UPDATE_OWNER_NAME = 'UPDATE_OWNER_NAME';
export const UPDATE_LOCATION = 'UPDATE_LOCATION';
export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const UPDATE_TERMS = 'UPDATE_TERMS';
export const SUBMIT_INFO = 'SUBMIT_INFO';

export const GET_INITIAL_DATE = 'GET_INITIAL_DATE';